### ISSUE TITLE
implement onImageTouchListener

### ISSUE THREAD

**Issue by splangi** [splangi/Gourmet#11]
When the helper image view is touched, we must get the pixel value from helper image and compare it to the lemmaword color (There is a field color in the LemmaWord object). If we found a match, we will create new AlertDialog with appropriate content. 

For details, see the ImageOnTouchListener class

**Comment by rkapp22** [comment]
Have some problems finding my way in the world of Java. uploaded my version with comments to the github...

**Comment by rkapp22** [comment]
should be done...
