### ISSUE TITLE
Find replacement images for the keywords from internet

### ISSUE THREAD

**Issue by splangi** [splangi/Gourmet#7]
Given the keywords, download images from the internet that we will use on the app

**Comment by splangi** [comment]
Rait wrote to me in email:

Mismoodi sa mõtled seda? 
Kas otsin välja hunniku sobilikke pilte, mis paneme programmikoodiga kaasa või peaks tarkvara ise otsima veebist sobilikud pildid ning lennult tegelema õigesse mõõtu seadmisega?

Sorry, this is in Estonian

**Comment by splangi** [comment]
At first I was thinking that we will search the internet and download the neccessary images manually and include them in the application (In small size, ca 10-50kb). This will be done for simplicity of the project. Web search will oppose many difficulties including copyright issues and did the downloaded image for keyword actually represents the keyword. For example "kana" will most probably give you a live image of chicken or farm or whatever but not a image of some meal of checken. Do we really want that? I think looking for images automatically from the web will be out of the scope of our project.

**Comment by splangi** [comment]
Collaboration with sven is neccessary for getting the keywords.

**Comment by svenaller** [comment]
We must collect popular images. "Kana" or "chicken" is more characteristic than the image from food. I will make the list the words and then we can decide, what is important, what is not. What is the amount of words?

**Comment by splangi** [comment]
I believe that initially 100 most popular keywords will be enough. The platform must be agile enough to handle image addition dynamically.

**Comment by svenaller** [comment]
OK. Rait (?) can find some pictures right now and test (size, quality etc) without list of words (bread, chicken... are in the list anyway). I made the lemmatizer interface for the morphological analizer (we will use it for find base form) and for example "hakklihakaste" (minced meat sauce) -> "hakk kaste liha", I hope the word "hakk" (jackdaw, crow) is not in the meaningful word's list... :D
